################### COPY FROM DEV-APPLICAIONT.YML FOR LOCAL RUN #########################
Log:
  entry:
    aspect:
      show-args: true
segment:
  writekey: ${SEGMENT_WRITE_KEY} #TODO generate source per env on segement
spring:
  application:
    name: changme #TODO change app name
  liquibase:
    change-log: classpath:db/db.master.xml
    drop-first: false
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWKS_URI} #TODO jkws url for auth server
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher #fixes a bug might not be needed after dependency update
application:
  search:
    pageSizeLimit: 100 #TODO change as needed
swagger:
  enabled: ${SWAGGER_ENABLED} #TODO only for dev