
spring:
  application:
    name: watcher
  datasource:
    url: jdbc:postgresql://localhost:5432/watcher
    username: postgres
    password: admin1234
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher #fixes a bug might not be needed after dependency update
twitter:
  baseUrl: https://api.twitter.com/2/
  token: AAAAAAAAAAAAAAAAAAAAAGe7CwEAAAAAE1KXMTzY0sDsD3gjU7o%2Bf1g%2B0Jk%3Da49vgJf4o2U7devf3v5I12yQWx3RxWBwdIRhlGPWvG7TwYG7tx
  id: 1288618920
swagger:
  enabled: true